In [1]:
import numpy as np

np.__version__

'1.19.2'

In [2]:
arr = np.arange(10)
arr.shape

(10,)

In [5]:
arr = np.array([[0, 1, 2, ], [3, 4, 5]])
arr.shape

(2, 3)

In [6]:
np.random.random(10)

array([0.38231771, 0.75778321, 0.12861306, 0.38894206, 0.15269124,
       0.85529939, 0.11987724, 0.76485662, 0.49630987, 0.79408374])

In [7]:
np.random.random((3, 3))

array([[0.58266739, 0.4294642 , 0.03781811],
       [0.93628438, 0.7077663 , 0.76332784],
       [0.92411764, 0.57009182, 0.70230343]])

In [9]:
np.random.randn(10, 10)

array([[-0.52790209, -0.60405038, -1.20020863,  0.30713507, -0.01502211,
         1.15334434, -1.2944237 ,  1.91050103, -0.68949464, -1.17562469],
       [-0.20593182, -1.78401499, -2.43221   , -0.20059109,  0.05987299,
        -0.51430523, -0.38221267, -1.79031241, -0.51816833, -0.53511099],
       [ 0.96719751, -0.13625452,  0.61699881,  2.31301857, -1.14287048,
         0.05692135, -0.95193796,  0.18427278,  1.62435839, -0.17990283],
       [ 1.17667883, -0.0248784 ,  1.12386645, -1.63665761, -1.24889804,
         1.0363803 , -1.08403956, -3.21197978, -1.04042768, -1.00765451],
       [ 1.5049206 , -0.94445019,  0.82639083, -0.56707984,  0.85177833,
        -0.10116492,  1.79931691,  0.68385163,  0.00582556, -0.88298579],
       [-2.08587004,  1.72444702,  1.56397563, -1.08523817,  0.27183605,
        -1.19972647,  0.16253776, -1.44385597,  1.06160853,  1.67840831],
       [ 1.29695044, -0.60542267,  1.40999929, -0.80564313,  0.44071838,
         0.27791547,  0.51236144, -2.01563184